// clang-format off

// AUTOGENERATED FILE, DO NOT EDIT
// Generated by https://roboticsbrno.github.io/Esp32-RBGridUI-Designer/
// Layout: {"cols":12,"rows":18,"enableSplitting":true,"widgets":[{"uuid":64246,"type":"Text","state":{"id":"PletackaInfo","x":1,"y":1,"w":6,"h":2,"css":{},"text":"Pletacka-IoT","fontSize":25,"color":"#000000","align":"end","valign":"center","prefix":"","suffix":""}},{"uuid":16128,"type":"Text","state":{"id":"numberInfo","x":8,"y":1,"w":2.5,"h":2,"css":{},"text":"1","fontSize":33,"color":"#000000","align":"center","valign":"center","prefix":"","suffix":""}},{"uuid":1401,"type":"Button","state":{"id":"rebootButton","x":2,"y":4.5,"w":3,"h":2.5,"css":{},"text":"Reboot"}},{"uuid":3185,"type":"Orientation","state":{"id":"Orientation1","x":3.5,"y":13,"w":5,"h":2,"css":{},"color":"#FF0000"}},{"uuid":32520,"type":"Text","state":{"id":"numberText","x":7,"y":5.5,"w":3,"h":0.5,"css":{},"text":"1","fontSize":12,"color":"#000000","align":"center","valign":"center","prefix":"","suffix":""}},{"uuid":13853,"type":"Button","state":{"id":"numberPlus","x":7,"y":4.5,"w":3,"h":1,"css":{},"text":"+"}},{"uuid":26857,"type":"Button","state":{"id":"numberMinus","x":7,"y":6,"w":3,"h":1,"css":{},"text":"-"}},{"uuid":58647,"type":"Led","state":{"id":"finLed","x":2.5,"y":8.5,"w":1,"h":1,"css":{},"color":"#00ff1e","on":false}},{"uuid":35160,"type":"Led","state":{"id":"stopLed","x":8.5,"y":8.5,"w":1,"h":1,"css":{},"color":"#ff0000","on":false}},{"uuid":40849,"type":"Text","state":{"id":"finText","x":1.5,"y":9.5,"w":3,"h":1,"css":{},"text":"Finished","fontSize":12,"color":"#000000","align":"center","valign":"center","prefix":"","suffix":""}},{"uuid":14930,"type":"Text","state":{"id":"stopText","x":7.5,"y":9.5,"w":3,"h":1,"css":{},"text":"Stop","fontSize":12,"color":"#000000","align":"center","valign":"center","prefix":"","suffix":""}},{"uuid":58446,"type":"Text","state":{"id":"stateText","x":4,"y":8,"w":4,"h":1,"css":{},"text":"STATE","fontSize":30,"color":"#f00000","align":"center","valign":"center","prefix":"","suffix":""}}]}

// Usage: include this file, where needed, and in *one* .cpp file,
// define also GRIDUI_LAYOUT_DEFINITION just before the layout like this:
//
//    #define GRIDUI_LAYOUT_DEFINITION
//    #include "layout.h"
//    using namespace gridui;
//
// The layout.h should also be the last included header. Then, in your code:
//
//    auto builder = Layout.begin();
//    builder.Button1.onPress([](Button&) { ... })
//    ...
//    builder.commit();

#pragma once

#include <esp_log.h>
#include "gridui.h"

namespace gridui {

#ifndef RB_GRIDUI_VERSION
#define RB_GRIDUI_VERSION 0x040000
#endif

static_assert(RB_GRIDUI_VERSION >= 0x040200,
    "Your RBGridUi library version is too low for this layout, please update to 040200.");

class _Layout;

namespace builder {
class _LayoutBuilder {
    friend class gridui::_Layout;

    _LayoutBuilder() :
        PletackaInfo(
            UI.text(1, 1, 6, 2, 64246)
                .text("Pletacka-IoT")
                .fontSize(25)
                .align("end")
        ),
        numberInfo(
            UI.text(8, 1, 2.5, 2, 16128)
                .text("1")
                .fontSize(33)
        ),
        rebootButton(
            UI.button(2, 4.5, 3, 2.5, 1401)
                .text("Reboot")
        ),
        Orientation1(
            UI.orientation(3.5, 13, 5, 2, 3185)
        ),
        numberText(
            UI.text(7, 5.5, 3, 0.5, 32520)
                .text("1")
        ),
        numberPlus(
            UI.button(7, 4.5, 3, 1, 13853)
                .text("+")
        ),
        numberMinus(
            UI.button(7, 6, 3, 1, 26857)
                .text("-")
        ),
        finLed(
            UI.led(2.5, 8.5, 1, 1, 58647)
                .color("#00ff1e")
        ),
        stopLed(
            UI.led(8.5, 8.5, 1, 1, 35160)
                .color("#ff0000")
        ),
        finText(
            UI.text(1.5, 9.5, 3, 1, 40849)
                .text("Finished")
        ),
        stopText(
            UI.text(7.5, 9.5, 3, 1, 14930)
                .text("Stop")
        ),
        stateText(
            UI.text(4, 8, 4, 1, 58446)
                .text("STATE")
                .fontSize(30)
                .color("#f00000")
        )
    {
    }

public:
    void commit();

    Text& PletackaInfo;
    Text& numberInfo;
    Button& rebootButton;
    Orientation& Orientation1;
    Text& numberText;
    Button& numberPlus;
    Button& numberMinus;
    Led& finLed;
    Led& stopLed;
    Text& finText;
    Text& stopText;
    Text& stateText;
};

}; // namespace builder

class _Layout {
    friend class builder::_LayoutBuilder;
public:
    _Layout() {}

    builder::_LayoutBuilder begin() {
        static bool called = false;
        if(called) {
            ESP_LOGE("GridUILayout", "Layout.begin() was called more than once, this is an error!");
        }
        called = true;
        return builder::_LayoutBuilder();
    }

    Text PletackaInfo;
    Text numberInfo;
    Button rebootButton;
    Orientation Orientation1;
    Text numberText;
    Button numberPlus;
    Button numberMinus;
    Led finLed;
    Led stopLed;
    Text finText;
    Text stopText;
    Text stateText;
};

extern _Layout Layout;
#ifdef GRIDUI_LAYOUT_DEFINITION
_Layout Layout;
#endif

namespace builder {

void _LayoutBuilder::commit() {
    Layout.PletackaInfo = PletackaInfo.finish();
    Layout.numberInfo = numberInfo.finish();
    Layout.rebootButton = rebootButton.finish();
    Layout.Orientation1 = Orientation1.finish();
    Layout.numberText = numberText.finish();
    Layout.numberPlus = numberPlus.finish();
    Layout.numberMinus = numberMinus.finish();
    Layout.finLed = finLed.finish();
    Layout.stopLed = stopLed.finish();
    Layout.finText = finText.finish();
    Layout.stopText = stopText.finish();
    Layout.stateText = stateText.finish();
    UI.commit();
}

};

};