// clang-format off

// AUTOGENERATED FILE, DO NOT EDIT
// Generated by https://roboticsbrno.github.io/Esp32-RBGridUI-Designer/
// Layout: {"cols":12,"rows":18,"enableSplitting":true,"widgets":[{"uuid":64246,"type":"Text","state":{"id":"PletackaInfo","x":0,"y":0,"w":7.5,"h":3,"css":{},"text":"Pletacka-IoT","fontSize":35,"color":"#000000","align":"center","valign":"center","prefix":"","suffix":""}},{"uuid":16128,"type":"Text","state":{"id":"numberInfo","x":7.5,"y":0,"w":4.5,"h":3,"css":{},"text":"1","fontSize":35,"color":"#000000","align":"start","valign":"center","prefix":"","suffix":""}},{"uuid":1401,"type":"Button","state":{"id":"rebootButton","x":1,"y":3.5,"w":3,"h":3,"css":{},"text":"Reboot"}},{"uuid":32520,"type":"Text","state":{"id":"numberText","x":6,"y":4.5,"w":3,"h":1,"css":{},"text":"1","fontSize":20,"color":"#000000","align":"center","valign":"center","prefix":"","suffix":""}},{"uuid":13853,"type":"Button","state":{"id":"numberPlus","x":6,"y":3.5,"w":3,"h":1,"css":{},"text":"+"}},{"uuid":26857,"type":"Button","state":{"id":"numberMinus","x":6,"y":5.5,"w":3,"h":1,"css":{},"text":"-"}},{"uuid":58647,"type":"Led","state":{"id":"finLed","x":2,"y":9.5,"w":1.5,"h":1.5,"css":{},"color":"#00ff1e","on":false}},{"uuid":35160,"type":"Led","state":{"id":"stopLed","x":8.5,"y":9.5,"w":1.5,"h":1.5,"css":{},"color":"#ff0000","on":false}},{"uuid":40849,"type":"Text","state":{"id":"finText","x":0.5,"y":11,"w":4.5,"h":1.5,"css":{},"text":"Finished","fontSize":25,"color":"#000000","align":"center","valign":"center","prefix":"","suffix":""}},{"uuid":14930,"type":"Text","state":{"id":"stopText","x":7,"y":11,"w":4.5,"h":1.5,"css":{},"text":"Stop","fontSize":25,"color":"#000000","align":"center","valign":"center","prefix":"","suffix":""}},{"uuid":58446,"type":"Text","state":{"id":"stateText","x":1,"y":7,"w":10,"h":2,"css":{},"text":"STATE","fontSize":40,"color":"#f00000","align":"center","valign":"center","prefix":"","suffix":""}},{"uuid":5894,"type":"Button","state":{"id":"numberSave","x":9,"y":3.5,"w":2,"h":3,"css":{},"text":"Save"}}]}

// Usage: include this file, where needed, and in *one* .cpp file,
// define also GRIDUI_LAYOUT_DEFINITION just before the layout like this:
//
//    #define GRIDUI_LAYOUT_DEFINITION
//    #include "layout.h"
//    using namespace gridui;
//
// The layout.h should also be the last included header. Then, in your code:
//
//    auto builder = Layout.begin();
//    builder.Button1.onPress([](Button&) { ... })
//    ...
//    builder.commit();

#pragma once

#include <esp_log.h>
#include "gridui.h"

namespace gridui {

#ifndef RB_GRIDUI_VERSION
#define RB_GRIDUI_VERSION 0x040000
#endif

static_assert(RB_GRIDUI_VERSION >= 0x040000,
    "Your RBGridUi library version is too low for this layout, please update to 040000.");

class _Layout;

namespace builder {
class _LayoutBuilder {
    friend class gridui::_Layout;

    _LayoutBuilder() :
        PletackaInfo(
            UI.text(0, 0, 7.5, 3, 64246)
                .text("Pletacka-IoT")
                .fontSize(35)
        ),
        numberInfo(
            UI.text(7.5, 0, 4.5, 3, 16128)
                .text("1")
                .fontSize(35)
                .align("start")
        ),
        rebootButton(
            UI.button(1, 3.5, 3, 3, 1401)
                .text("Reboot")
        ),
        numberText(
            UI.text(6, 4.5, 3, 1, 32520)
                .text("1")
                .fontSize(20)
        ),
        numberPlus(
            UI.button(6, 3.5, 3, 1, 13853)
                .text("+")
        ),
        numberMinus(
            UI.button(6, 5.5, 3, 1, 26857)
                .text("-")
        ),
        finLed(
            UI.led(2, 9.5, 1.5, 1.5, 58647)
                .color("#00ff1e")
        ),
        stopLed(
            UI.led(8.5, 9.5, 1.5, 1.5, 35160)
                .color("#ff0000")
        ),
        finText(
            UI.text(0.5, 11, 4.5, 1.5, 40849)
                .text("Finished")
                .fontSize(25)
        ),
        stopText(
            UI.text(7, 11, 4.5, 1.5, 14930)
                .text("Stop")
                .fontSize(25)
        ),
        stateText(
            UI.text(1, 7, 10, 2, 58446)
                .text("STATE")
                .fontSize(40)
                .color("#f00000")
        ),
        numberSave(
            UI.button(9, 3.5, 2, 3, 5894)
                .text("Save")
        )
    {
    }

public:
    void commit();

    Text& PletackaInfo;
    Text& numberInfo;
    Button& rebootButton;
    Text& numberText;
    Button& numberPlus;
    Button& numberMinus;
    Led& finLed;
    Led& stopLed;
    Text& finText;
    Text& stopText;
    Text& stateText;
    Button& numberSave;
};

}; // namespace builder

class _Layout {
    friend class builder::_LayoutBuilder;
public:
    _Layout() {}

    builder::_LayoutBuilder begin() {
        static bool called = false;
        if(called) {
            ESP_LOGE("GridUILayout", "Layout.begin() was called more than once, this is an error!");
        }
        called = true;
        return builder::_LayoutBuilder();
    }

    Text PletackaInfo;
    Text numberInfo;
    Button rebootButton;
    Text numberText;
    Button numberPlus;
    Button numberMinus;
    Led finLed;
    Led stopLed;
    Text finText;
    Text stopText;
    Text stateText;
    Button numberSave;
};

extern _Layout Layout;
#ifdef GRIDUI_LAYOUT_DEFINITION
_Layout Layout;
#endif

namespace builder {

void _LayoutBuilder::commit() {
    Layout.PletackaInfo = PletackaInfo.finish();
    Layout.numberInfo = numberInfo.finish();
    Layout.rebootButton = rebootButton.finish();
    Layout.numberText = numberText.finish();
    Layout.numberPlus = numberPlus.finish();
    Layout.numberMinus = numberMinus.finish();
    Layout.finLed = finLed.finish();
    Layout.stopLed = stopLed.finish();
    Layout.finText = finText.finish();
    Layout.stopText = stopText.finish();
    Layout.stateText = stateText.finish();
    Layout.numberSave = numberSave.finish();
    UI.commit();
}

};

};